### ISSUE TITLE
Error on compress image.

### ISSUE THREAD

**Issue by marcossaore** [MichaelSolati/nativescript-ffmpeg#3]
I´m doing app which records a interview with plugin nativescript-recorder but after record, the output file size is very big. I want  to compress it to send it to server.
I´m facing troubles when I use the comand execute which doesn´t compress file.

__It seems this algorithm enter on both conditionals__

## MY SMARTPHONE:
    MOTO X 2nd

## MY CODE:
 ``` 
this.recorder.on("finished", args => {
      clearInterval(this.interval);
      if (this.get("duration")) {
        const file = args.object.get('file');
        this._compress(file);
      }
   });

  private _compress(src: string): void {
   
    console.log("Original file size " + this._getSize(src));

    const out =  src.replace(/\.[^/.]+$/, "_COMPRESSED.mp4");
    FFmpeg.execute(["-i", src, "-vcodec", "h264", "-acodec", "mp4", out], (err) => {
      if (err) {
        console.log(err);
        console.log('it was error')
     } else {
        console.log(src);
        console.log(out);
        console.log("Compressed file size " + this._getSize(out));
      }
    });
  }

  private _getSize(path: string): string {
    let length: number = 0;
    if (isAndroid) {
      const file = new java.io.File(path);
      length = file.length();
    } else {
      const defManager = NSFileManager.defaultManager;
      const fileAttributes = defManager.attributesOfItemAtPathError(path);
      length = fileAttributes.objectForKey(NSFileSize);
    }
    return `${(length / (1000 * 1000)).toFixed(2)} MB`;
  }

 ``` 

![error](https://user-images.githubusercontent.com/13766539/43963547-f6bf9cfe-9c90-11e8-9a35-6698751a4e50.png)

**Comment by MichaelSolati** [comment]
@marcossaore unfortunately I'm not intending on supporting this package at this time. I'm open to PRs and someonelse wanting to jump in, just unfortunately I don't have the time or ability to address this. 😢

Also, have you tried other commands to see how compression could/would work?

**Comment by marcossaore** [comment]
@MichaelSolati  All right, I will try another way to do this. 
No, I dont try. I just got your code and put it in my logic, I will try learn about ffmpeg concepts because  it´s first time that I deal compress video file.
thanks for answering!!

**Comment by MichaelSolati** [comment]
@marcossaore any update? I'm inclined to close the issue if I don't hear anything back.

**Comment by marcossaore** [comment]
I gave up for now.  I will close it.
